// @license MIT
// Shared OpenAPI → endpoint-catalog logic, used by generate-endpoints.mjs
// (writes the generated files) and sync-openapi.mjs (diffs old vs new).
//
// Torn API v2 is path-based: each data type is its own GET operation. We fully
// dereference the spec ($ref / allOf / oneOf / anyOf) and build, per tag, an
// authoritative catalog of endpoints with summaries, path id, and query params.
import { createHash } from "node:crypto";

function makeResolver(spec) {
  const resolveRef = (ref) => {
    const parts = ref.replace(/^#\//, "").split("/");
    let node = spec;
    for (const p of parts) node = node?.[p];
    return node;
  };
  const deref = (node, seen = new Set()) => {
    if (node && node.$ref) {
      if (seen.has(node.$ref)) return {};
      seen.add(node.$ref);
      return deref(resolveRef(node.$ref), seen);
    }
    return node ?? {};
  };
  const collectEnum = (node, acc = new Set(), seen = new Set()) => {
    if (!node) return acc;
    if (node.$ref) {
      if (seen.has(node.$ref)) return acc;
      seen.add(node.$ref);
      return collectEnum(resolveRef(node.$ref), acc, seen);
    }
    if (Array.isArray(node.enum)) node.enum.forEach((e) => acc.add(e));
    for (const key of ["oneOf", "anyOf", "allOf"]) {
      if (Array.isArray(node[key])) node[key].forEach((n) => collectEnum(n, acc, seen));
    }
    if (node.items) collectEnum(node.items, acc, seen);
    return acc;
  };
  const typeOf = (schema, seen = new Set()) => {
    if (!schema) return "string";
    if (schema.$ref) {
      if (seen.has(schema.$ref)) return "string";
      seen.add(schema.$ref);
      return typeOf(resolveRef(schema.$ref), seen);
    }
    if (Array.isArray(schema.enum)) return "enum";
    if (schema.type === "array") return `array<${typeOf(schema.items, seen)}>`;
    for (const key of ["oneOf", "anyOf"]) {
      if (Array.isArray(schema[key])) {
        return [...new Set(schema[key].map((s) => typeOf(s, seen)))].join("|");
      }
    }
    if (Array.isArray(schema.allOf)) return typeOf(schema.allOf[0], seen);
    return schema.type || "string";
  };
  const describeParam = (rawParam) => {
    const p = deref(rawParam);
    const schema = p.schema ?? {};
    const enumVals = [...collectEnum(schema)];
    const out = {
      name: p.name,
      in: p.in,
      required: !!p.required,
      type: typeOf(schema),
      description: (p.description || "").trim() || undefined,
    };
    if (enumVals.length > 0) out.enum = enumVals;
    return out;
  };
  return { describeParam };
}

/** Build the tag → endpoint catalog from a parsed OpenAPI spec. */
export function buildCatalog(spec) {
  const { describeParam } = makeResolver(spec);
  const tags = {};

  for (const rawPath of Object.keys(spec.paths || {})) {
    const op = spec.paths[rawPath].get;
    if (!op) continue;
    const tag = ((op.tags && op.tags[0]) || "untagged").toLowerCase();

    const segs = rawPath.split("/").filter(Boolean);
    if (segs.length < 2) continue;
    const hasParam = segs.some((s) => s.startsWith("{"));
    const name = [...segs].reverse().find((s) => !s.startsWith("{"));
    if (!name || name === tag) continue;

    const params = (op.parameters || []).map(describeParam);
    const pathParam = params.find((p) => p.in === "path");
    const query = params.filter((p) => p.in === "query" && !(p.in === "query" && p.name === "key"));

    tags[tag] = tags[tag] || {};
    const entry = tags[tag][name] || {
      requiresId: false,
      summary: (op.summary || "").trim() || undefined,
      description: (op.description || "").trim() || undefined,
      query,
    };
    if (hasParam) {
      entry.idPath = rawPath;
      if (pathParam) entry.idParam = { name: pathParam.name, description: pathParam.description };
    } else {
      entry.path = rawPath;
      entry.summary = (op.summary || "").trim() || entry.summary;
      entry.description = (op.description || "").trim() || entry.description;
      entry.query = query;
    }
    tags[tag][name] = entry;
  }

  for (const tag of Object.keys(tags)) {
    for (const nm of Object.keys(tags[tag])) {
      const e = tags[tag][nm];
      e.requiresId = !e.path && !!e.idPath;
    }
  }

  const tagList = Object.keys(tags).sort();
  const endpoints = tagList.reduce((n, t) => n + Object.keys(tags[t]).length, 0);
  return {
    tags,
    tagList,
    openapiVersion: spec?.info?.version ?? "unknown",
    endpoints,
  };
}

/** SHA-256 hex of the raw spec text. */
export function specHashOf(specText) {
  return createHash("sha256").update(specText).digest("hex");
}

export function renderEndpointsTs(catalog) {
  const { tags, tagList } = catalog;
  let out =
    "// @license MIT\n" +
    "// AUTO-GENERATED by scripts/generate-endpoints.mjs — do not edit by hand.\n" +
    "// Fully dereferenced from openapi.json ($ref/allOf/oneOf/anyOf resolved).\n" +
    "// Regenerate with: npm run sync-openapi\n";
  out += `
export interface QueryParam {
  name: string;
  in: "query";
  required: boolean;
  type: string;
  enum?: string[];
  description?: string;
}

export interface EndpointDef {
  /** Path without an id (when the endpoint supports it). */
  path?: string;
  /** Path template containing a single {param} placeholder. */
  idPath?: string;
  /** The path parameter, when this endpoint is id-scoped. */
  idParam?: { name: string; description?: string };
  /** True when the endpoint can only be called with an id. */
  requiresId: boolean;
  /** Operation summary from the spec. */
  summary?: string;
  /** Operation description from the spec. */
  description?: string;
  /** Accepted query parameters (auth key excluded). */
  query: QueryParam[];
}
`;
  out += `\nexport const ENDPOINTS = ${JSON.stringify(tags, null, 2)} as const satisfies Record<string, Record<string, EndpointDef>>;\n`;
  out += `\nexport type TornTag = keyof typeof ENDPOINTS;\n`;
  out += `\nexport const TAGS = ${JSON.stringify(tagList)} as const;\n`;
  return out;
}

export function renderManifestTs(catalog, specHash) {
  return (
    "// @license MIT\n" +
    "// AUTO-GENERATED by scripts/generate-endpoints.mjs — do not edit by hand.\n" +
    "// Identifies the Torn OpenAPI spec this build was generated from.\n\n" +
    `export const MANIFEST = {\n` +
    `  openapiVersion: ${JSON.stringify(catalog.openapiVersion)},\n` +
    `  specHash: ${JSON.stringify(specHash)},\n` +
    `  tags: ${catalog.tagList.length},\n` +
    `  endpoints: ${catalog.endpoints},\n` +
    `} as const;\n`
  );
}

/** Stable structural signature of an endpoint (ignores summary/description text). */
function signature(entry) {
  return JSON.stringify({
    path: entry.path ?? null,
    idPath: entry.idPath ?? null,
    requiresId: entry.requiresId,
    query: (entry.query || [])
      .map((q) => ({ n: q.name, req: q.required, en: (q.enum || []).slice().sort() }))
      .sort((a, b) => (a.n < b.n ? -1 : 1)),
  });
}

function flatKeys(tags) {
  const map = new Map();
  for (const tag of Object.keys(tags)) {
    for (const name of Object.keys(tags[tag])) map.set(`${tag}/${name}`, tags[tag][name]);
  }
  return map;
}

/** Diff two catalogs. Returns version delta, tag delta, and endpoint deltas. */
export function diffCatalogs(oldCat, newCat) {
  const oldMap = flatKeys(oldCat.tags);
  const newMap = flatKeys(newCat.tags);
  const added = [];
  const removed = [];
  const changed = [];
  let unchanged = 0;

  for (const key of newMap.keys()) {
    if (!oldMap.has(key)) added.push(key);
    else if (signature(oldMap.get(key)) !== signature(newMap.get(key))) changed.push(key);
    else unchanged++;
  }
  for (const key of oldMap.keys()) {
    if (!newMap.has(key)) removed.push(key);
  }

  const oldTags = new Set(oldCat.tagList);
  const newTags = new Set(newCat.tagList);
  return {
    oldVersion: oldCat.openapiVersion,
    newVersion: newCat.openapiVersion,
    versionChanged: oldCat.openapiVersion !== newCat.openapiVersion,
    addedTags: newCat.tagList.filter((t) => !oldTags.has(t)),
    removedTags: oldCat.tagList.filter((t) => !newTags.has(t)),
    added: added.sort(),
    removed: removed.sort(),
    changed: changed.sort(),
    unchanged,
    oldCount: oldMap.size,
    newCount: newMap.size,
    hasChanges:
      added.length > 0 ||
      removed.length > 0 ||
      changed.length > 0 ||
      oldCat.openapiVersion !== newCat.openapiVersion,
  };
}

/** Render a human-readable change report (Markdown). */
export function renderReport(diff) {
  const lines = [];
  const v = diff.versionChanged
    ? `${diff.oldVersion} → ${diff.newVersion}`
    : `${diff.newVersion} (unchanged)`;
  lines.push(`**OpenAPI version:** ${v}`);
  lines.push(
    `**Endpoints:** ${diff.oldCount} → ${diff.newCount} ` +
      `(+${diff.added.length} added, -${diff.removed.length} removed, ` +
      `${diff.changed.length} changed, ${diff.unchanged} unchanged)`,
  );
  if (diff.addedTags.length) lines.push(`**New tags:** ${diff.addedTags.join(", ")}`);
  if (diff.removedTags.length) lines.push(`**Removed tags:** ${diff.removedTags.join(", ")}`);
  if (diff.added.length) lines.push(`**Added:** ${diff.added.join(", ")}`);
  if (diff.removed.length) lines.push(`**Removed:** ${diff.removed.join(", ")}`);
  if (diff.changed.length) lines.push(`**Changed (params/enums):** ${diff.changed.join(", ")}`);
  return lines.join("\n");
}
