// @license MIT
// README sections that are derived from the catalog. Regenerated by
// generate-endpoints.mjs and sync-openapi.mjs; the contract test fails when the
// committed README no longer matches the committed catalog.

export const TOOLS_START = "<!-- tools:start -->";
export const TOOLS_END = "<!-- tools:end -->";

/** A few representative endpoint names per tag (first entries, catalog order). */
const EXAMPLES = 6;

/**
 * Markdown table: one grouped tool per tag, largest first, plus the discovery
 * tool. Columns are padded the way Prettier formats tables, so running
 * `prettier --write README.md` is a no-op and the contract test stays exact.
 */
export function renderToolTable(catalog) {
  const rows = [...catalog.tagList]
    .map((tag) => ({ tag, names: Object.keys(catalog.tags[tag]) }))
    .sort((a, b) => b.names.length - a.names.length || a.tag.localeCompare(b.tag));
  const cells = [["Tool", "Endpoints", "Example `endpoint` values"]];
  for (const r of rows) {
    const examples = r.names.slice(0, EXAMPLES).map((n) => `\`${n}\``).join(", ");
    cells.push([`\`torn_${r.tag}\``, String(r.names.length), examples]);
  }
  cells.push(["`torn_list_endpoints`", "—", "discovery: lists every endpoint per tag"]);
  const widths = cells[0].map((_, i) => Math.max(...cells.map((row) => [...row[i]].length)));
  const pad = (s, w) => s + " ".repeat(w - [...s].length);
  const line = (row) => `| ${row.map((c, i) => pad(c, widths[i])).join(" | ")} |`;
  const sep = `| ${widths.map((w) => "-".repeat(w)).join(" | ")} |`;
  return [line(cells[0]), sep, ...cells.slice(1).map(line)].join("\n");
}

const COUNT_RE = /covering all \d+ endpoints across \d+ operations of the spec/g;

/**
 * Rewrite the marked tool-table block and the "covering all N endpoints across
 * M operations" sentence. Throws when the markers are missing so a hand-edited
 * README cannot drift silently.
 */
export function syncReadme(text, catalog) {
  const start = text.indexOf(TOOLS_START);
  const end = text.indexOf(TOOLS_END);
  if (start < 0 || end < 0 || end < start) {
    throw new Error(`README is missing the ${TOOLS_START} / ${TOOLS_END} markers.`);
  }
  // Blank lines around the table match Prettier's markdown output exactly; the
  // README's own line ending (CRLF in this repo) is preserved.
  const eol = text.includes("\r\n") ? "\r\n" : "\n";
  const table = renderToolTable(catalog).split("\n").join(eol);
  const block = `${TOOLS_START}${eol}${eol}${table}${eol}${eol}${TOOLS_END}`;
  const replaced = text.slice(0, start) + block + text.slice(end + TOOLS_END.length);
  return replaced.replace(
    COUNT_RE,
    `covering all ${catalog.endpoints} endpoints across ${catalog.rawOps} operations of the spec`,
  );
}
